### ISSUE TITLE
Test - Django-Filer 2.1rc1

### ISSUE THREAD

**Issue by jbpenrath** [django-cms/django-filer#1227]
I'm testing Django Filer 2.1rc1 which introduces SVG upload support.
Globaly all is working pretty well, I just encountered little issues related to the dropzone layout.

![layout-dropzone-1](https://user-images.githubusercontent.com/9265241/100742476-249c2780-33db-11eb-92c4-f57fafa6066c.png)
![layout-dropzone](https://user-images.githubusercontent.com/9265241/100742478-25cd5480-33db-11eb-89bd-cfde77fa2334.png)

#### Configuration
**OS**: Mac OS 10.15.7
**Browser**: Firefox 83.0
**Resolution**: 2560x1440

**Comment by jrief** [comment]
This is how it looks on Firefox 80.0.1 on my Mac OS 10.15.7:
![Screenshot 2020-12-01 at 23 09 26](https://user-images.githubusercontent.com/1132472/100802795-538dba00-342a-11eb-82d4-1d0779e7b79d.png)
![Screenshot 2020-12-01 at 23 05 15](https://user-images.githubusercontent.com/1132472/100802481-da8e6280-3429-11eb-844d-acb46f41d1e0.png)

The broken layout presumably is caused by your CMS plugin implementing a picture. I use a special PicturePlugin from [djangocms-cascade](https://github.com/jrief/djangocms-cascade), there I adopted some CSS for the modal editor.

```css
#content-main form .form-row #id_source, #content-main form .form-row #id_alt_tag {
    width: calc(100% - 180px);
}

#content-main form .form-row.field-alt_tag, #content-main form .form-row.field-source {
    border-bottom: none;
}

#content-main form .form-row.field-empty_alt_tag, #content-main form .form-row.field-empty_source > .checkbox-row {
    margin-left: 170px;
}
```

Since I don't know which Picture Plugin you are using, please open a pull request there and add the CSS snippet from above, to fix those problems.
